language: php
php:
  - '7.0'
  - '7.1'
install:
  # We need a full Drupal project for our Kernel tests to work. Create a new project.
  - composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
  # Our code is no longer in the correct place. Copy it over.
  - mkdir -p drupal/web/modules/form_validation && cp -a form_validation* tests src drupal/web/modules/form_validation
script:
  - drupal/vendor/bin/phpunit -c drupal/web/core drupal/web/modules/form_validation/tests/ --coverage-clover clover.xml
